### PR TITLE
adding private attribute for guides

### PR DESCRIPTION
**Pull request by luchotc**
Also, after deploying this version we should run this query:

```
db.guides.updateMany(
    {
        "$or": [
            { "private": { "$exists": false } }, 
            { "private": null }
        ]
    }, 
    { "$set": { "private": false } }
)
```

### CODE REVIEW

**Comment by flbulgarelli** [comment]
Can we do something to handle `private: null` as `private: false` and void a migration?

**Comment by flbulgarelli** [comment]
The rest of the PR looks fine

**Comment by luchotc** [comment]
It works fine without the migration, i proposed it just to keep things consistent.

**Comment by flbulgarelli** [comment]
> It works fine without the migration, i proposed it just to keep things consistent.

You rock :metal:

**Pull request merged**
